// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qulztlnpbixlqrhrhhyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bHp0bG5wYml4bHFyaHJoaHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMzk5ODgsImV4cCI6MjA1MzcxNTk4OH0.8xkJL6WXpFlRerBzPtiYdFe9jExg9-om8uTefj0vwVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);